### ISSUE TITLE
Update Oculus

### ISSUE THREAD

**Issue by MAXimized490** [MAXimized490/MandA-BofM#136]
Current Version: `1.6.13`
~~New Version: `1.7.0`~~
New Version: `1.6.15a`
Comments (optional):

**Comment by MAXimized490** [comment]
1.7.0 Current

**Comment by MAXimized490** [comment]
Going past 1.6.15 causes errors.

**Comment by MAXimized490** [comment]
Got to 1.6.15a after updating to Embeddium to 0.3.5.

**Comment by MAXimized490** [comment]
On latest release, 1.7.0, Minecraft crashes during startup with `java.lang.NoClassDefFoundError: com/seibel/distanthorizons/api/interfaces/override/rendering/IDhApiShadowCullingFrustum`. 1.6.15a doesn't give any issues.
